'use client';

import { useMyProfile } from '@/hooks/use-employees';
import { useMyPayroll, useSalaryStructure } from '@/hooks/use-payroll';
import { formatPaise, MONTH_NAMES } from '@/lib/format';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { EmptyState } from '@/components/ui/empty-state';
import { TableSkeleton, Skeleton } from '@/components/ui/skeleton';

export default function PayrollPage() {
  const { data: profile } = useMyProfile();
  const { data: structure, isLoading: structureLoading } = useSalaryStructure(profile?.id);
  const { data: payrolls, isLoading: payrollLoading } = useMyPayroll();

  return (
    <div className="flex flex-col gap-8">
      <div>
        <h1 className="font-serif text-[38px] font-normal tracking-tight text-off-black">Payroll</h1>
        <p className="mt-1.5 text-[15px] text-graphite">Read-only — Admin manages your salary structure.</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Current salary structure</CardTitle>
        </CardHeader>
        <CardContent>
          {structureLoading ? (
            <Skeleton className="h-20 w-full" />
          ) : !structure ? (
            <EmptyState title="Not set up yet" description="Your Admin hasn't defined a salary structure." />
          ) : (
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
              <Amount label="Basic" value={structure.basic} />
              <Amount label="HRA" value={structure.hra} />
              <Amount label="Allowances" value={structure.allowances} />
              <Amount label="Deductions" value={-structure.deductions} />
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Payslips</CardTitle>
          <CardDescription>Generated by Admin each pay cycle.</CardDescription>
        </CardHeader>
        <CardContent>
          {payrollLoading ? (
            <TableSkeleton />
          ) : !payrolls || payrolls.data.length === 0 ? (
            <EmptyState title="No payslips yet" />
          ) : (
            <div className="flex flex-col divide-y divide-line">
              {payrolls.data.map((p) => (
                <div key={p.id} className="flex items-center justify-between gap-4 py-4">
                  <div>
                    <p className="text-[16px] text-off-black">
                      {MONTH_NAMES[p.month - 1]} {p.year}
                    </p>
                    <p className="text-[12px] text-graphite">
                      Basic {formatPaise(p.basic)} · HRA {formatPaise(p.hra)} · Allowances{' '}
                      {formatPaise(p.allowances)} · Deductions {formatPaise(p.deductions)}
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="font-serif text-[24px] font-normal tracking-tight tabular-nums text-off-black">
                      {formatPaise(p.net)}
                    </p>
                    <p className="text-[12px] uppercase tracking-[0.04em] text-smoke">Net pay</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

function Amount({ label, value }: { label: string; value: number }) {
  return (
    <div className="flex flex-col gap-1">
      <span className="text-[12px] uppercase tracking-[0.04em] text-smoke">{label}</span>
      <span className="font-serif text-[20px] tracking-tight tabular-nums text-off-black">{formatPaise(value)}</span>
    </div>
  );
}
